{% set name = "http3" %}
{% set version = "0.6.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbf9beedc58d8bbcf6e681a9d63d9e7cd8da346e1ffb512e02e9bf097d91f0bf

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - certifi
    - chardet ==3.*
    - h11 ==0.8.*
    - h2 ==3.*
    - idna ==2.*
    - python >={{ python_min }}
    - rfc3986 ==1.*

test:
  requires:
    - python {{ python_min }}
  imports:
    - http3
    - http3.dispatch

about:
  home: https://github.com/encode/http3
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.

extra:
  recipe-maintainers:
    - nicoddemus
